DoctorAwards/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('',include('awards.urls')),
    #path("data-browser/", include("data_browser.urls")),
]

awards/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('doctor', views.DoctorHome.as_view(), name='doctors'),
    path('doct/<int:pk>/', views.DoctorDetailView.as_view(), name='doctor-detail'),
    path('report/', views.all_report,name='all_report'),
    path('report/form/',views.form_report,name='form_report'),
    #path('/report/<int:year>/', views.year_report),
]

awards/models.py
from django.db import models
from django.urls import reverse
from django.forms import ModelForm

class Lpu(models.Model):
  code_lpu = models.IntegerField(verbose_name='Код лпу')
  name_lpu = models.CharField(max_length=200,verbose_name='Наименование')

  def __str__(self):
    return self.name_lpu
  
  class Meta:
    verbose_name = 'ЛПУ'
    verbose_name_plural = 'ЛПУ'
        
  @property  
  def count_doctors(self):
    return self.doctors.count()
  

class Post(models.Model):
  name_post = models.CharField(max_length=150,verbose_name='Наименование')

  def __str__(self):
        return self.name_post

  class Meta:
    verbose_name = 'Должность'
    verbose_name_plural = 'Должности'     

class Doctor(models.Model):
  lastname = models.CharField(max_length=100,verbose_name='Фамилия')
  firstname = models.CharField(max_length=100,verbose_name='Имя')
  fathername = models.CharField(max_length=100,verbose_name='Отчество')
  birthday = models.DateField(verbose_name='Дата рождения')
  lpu = models.ForeignKey('Lpu', on_delete=models.PROTECT,related_name='doctors',verbose_name='ЛПУ')
  post = models.ForeignKey('Post', on_delete=models.PROTECT,verbose_name='Должность')
  experience_all = models.IntegerField(verbose_name='общий')
  experience_branch = models.IntegerField(verbose_name='в отрасли')
  experience_last = models.IntegerField(verbose_name='на последнем месте')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
      return '%s %s %s %s' % (self.lastname, self.firstname,self.fathername,self.birthday.strftime("%m.%d.%Y")) 
  def get_absolute_url(self):
    return reverse('doctor-detail', kwargs={'pk': self.pk})
  @property  
  def count_awards(self):
    return self.award.count()    

  class Meta:
    verbose_name = 'Сотрудник'
    verbose_name_plural = 'Сотрудники'     

class DoctorForm(ModelForm):
    class Meta:
        model = Doctor
        fields = ['lastname', 'birthday']

class Award(models.Model):
  AWARD_STATUS = (
      ('draft','На расмотрении'),
      ('refused','Отклонен'),
      ('approved','Подтвержден')
    )

  incoming_num = models.IntegerField(verbose_name='Вх. №')
  incoming_date = models.DateField(verbose_name='Вх. дата')
  doctor = models.ForeignKey('Doctor', on_delete=models.PROTECT,related_name='award',verbose_name='Сотрудник')
  type_award = models.ForeignKey('AwardType',on_delete=models.PROTECT,verbose_name='Тип награды')
  year_award = models.IntegerField(verbose_name='Год награды')
  number_award = models.CharField(max_length=50,verbose_name='Номер приказа',null=True,blank=True)
  date_order_award = models.DateField(verbose_name='Дата приказа',null=True,blank=True)  
  status = models.CharField(max_length=10,choices=AWARD_STATUS)
  refused_text = models.CharField(max_length=200,verbose_name="Причина отказа",null=True,blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return str(self.type_award) + ' №' + str(self.incoming_num) + ' от ' + self.incoming_date.strftime("%d.%m.%Y")

 

  class Meta:
    verbose_name = 'Награда'
    verbose_name_plural = 'Награды'    
    ordering = ['-incoming_date']

class AwardType(models.Model):
  awardtype_name = models.CharField(max_length=50)

  def __str__(self):
      return self.awardtype_name

  class Meta:
    verbose_name = 'Вид наград'
    verbose_name_plural = 'Виды нарад'  

awards/forms.py
from django import forms
from datetime import datetime
from .models import Lpu,Award
from bootstrap_datepicker_plus import DatePickerInput
from easy_select2.widgets import Select2
from bootstrap_datepicker_plus import DatePickerInput

class DoctorSearchForm(forms.Form):
    lastname = forms.CharField(required=False,label='Фамилия')

class DoctorReportForm(forms.Form):    
    incomDateB = forms.DateField(label='Дата вх. от',widget=forms.SelectDateWidget())
    incomDateE = forms.DateField(required=False,label='Дата вх. до',widget=forms.SelectDateWidget())
    #lpu = forms.ModelChoiceField(queryset=Lpu.objects.all(),widget=Select2())

class AwardSearchForm(forms.Form):
    start_date = forms.DateField(label='Дата вх. от',required=False,widget=DatePickerInput(format='%Y-%m-%d'))
    end_date = forms.DateField(required=False,label='Дата вх. до',widget=DatePickerInput(format='%Y-%m-%d'))
    export_to_xlsx_pivot = forms.BooleanField(required=False,label='Выгрузить сводный отчет')

awards/views.py
from django.db import models
from django.shortcuts import render, redirect
from django.views.generic import ListView,DetailView
from .models import Doctor,Award
from .forms import AwardSearchForm
import pandas as pd
from django.http import HttpResponse



#DataFlair
def index(request):
    return render(request, 'index.html')

class DoctorHome(ListView):
    model = Doctor
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = self.model.objects.filter(lastname__icontains=query)
        else:
            object_list = self.model.objects.all()
        return object_list

class DoctorDetailView(DetailView):
    model = Doctor

def all_report(request):
    qs = Award.objects.filter(incoming_date__range=["2021-01-01", "2021-07-31"]).values("doctor__lpu__name_lpu", "type_award__awardtype_name", "status")
    data = pd.DataFrame(qs)
    res = pd.pivot_table(data,index='doctor__lpu__name_lpu',columns='type_award__awardtype_name',values='status', aggfunc='count',margins=True, margins_name='Всего', fill_value=0)
    return HttpResponse(res.to_html())


def form_report(request):
    queryset = Award.objects.all()
    form = AwardSearchForm(request.POST or None)
    export_pivot = request.POST.get('export_to_xlsx_pivot', False)
    export_xlsx = request.POST.get('export_to_xlsx', False)
    if request.method == "POST":
        if(export_pivot):
            qs = Award.objects.filter(
                incoming_date__range=[
                    request.POST['start_date'], 
                    request.POST['end_date']]).values("doctor__lpu__name_lpu", "type_award__awardtype_name", "status")
            data = pd.DataFrame(qs)
            res = pd.pivot_table(data,index='doctor__lpu__name_lpu',columns='type_award__awardtype_name',values='status', aggfunc='count',margins=True, margins_name='Всего', fill_value=0)
            response = HttpResponse(content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename=your_template_name.xlsx'
            res.to_excel(response)
            return response
            
        if(request.POST['start_date'] and request.POST['end_date']):
            queryset = Award.objects.filter(            
                incoming_date__range=[
                    request.POST['start_date'],
                    request.POST['end_date']
                ]
            )


    context = {
        "queryset" : queryset,
        "form" : form
    }
    
    return render(request,'awards/search.html',context)

awards/templates/awards/doctor_detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}
<table class="table" border="1">
	<tbody>
		<tr>
			<td colspan="6"><b>Вх. {{object.award.first.incoming_num}}</b></td>
		</tr>
		<tr>
			<td><b>Поступил</b></td>
			<td>{{object.award.first.type_award}}</td>
      {% if object.award.first.status == "refused" %}
        <td><b>Награжден</b></td>
        <td>Отказ</td>
        <td><b>причина отказа</b></td>
        <td>{{object.award.first.refused_text}}</td>
      {% elif object.award.first.status == "draft" %}
        <td><b>Награжден</b></td>
        <td>На расмотрении</td>
        <td><b>причина отказа</b></td>
        <td</td>
      {% else %}
        <td><b>Награжден</b></td>
        <td>№{{object.award.first.number_award}} от {{object.award.first.date_order_award}}</td>
        <td><b>причина отказа</b></td>
        <td></td>
      {% endif %}			
		</tr>
		<tr>
			<td align="center"><b>ФИО</b></td>
			<td colspan="5">{{ object.lastname }} {{ object.firstname }} {{ object.fathername }} </td>
		</tr>
		<tr>
			<td align="center"><b>дата рождения</b></td>
			<td colspan="5">{{ object.birthday|date }}</td>
		</tr>
		<tr>
			<td align="center"><b>должность</b></td>
			<td colspan="5">{{ object.post }}</td>
		</tr>
		<tr>
			<td align="center"><b>учреждение</b></td>
			<td colspan="5">{{ object.lpu }}</td>
		</tr>
		<tr>
			<td align="center"><b>стаж</b></td>
			<td colspan="5">{{object.experience_all }} - {{ object.experience_branch }} - {{ object.experience_last }}<br/> (Общий; в отрасли; на последнем месте)</td>
		</tr>
		<tr>
			<td colspan="6"><b>имющиеся нарграды по годам:</b></td>
		</tr>
    {% for award in object.award.all %}
      <tr>
        <td colspan="6">{{ award }}</td>
      </tr>
    {% endfor %} 		
	</tbody>
</table>  
<!--
  <h1>Награды</h1>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">имющиеся нарграды по годам:</th>
    </tr>
  </thead>
  <tbody>
    {% for award in object.award_set.all %}
      <tr>
        <th scope="row">1</th>
        <td>{{ award }}</td>
      </tr>
    {% endfor %}    
  </tbody>
</table>-->
{% endblock %}

awards/templates/awards/doctor_list.html
  
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
    <h1>Список врачей</h1>
<form method='GET'>
  <input type='text' name='q' value='{{ request.GET.q }}'>
  <input class="button" type='submit' value="Поиск">
</form>
<br/>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">ФИО ДР</th>
    </tr>
  </thead>
  <tbody>
    {% for doct in object_list %}
    <tr>
      <td>#</td>
      <td><a href="{{ doct.get_absolute_url }}">{{ doct }} {{ doct.birthday|date }} ({{doct.lpu}})</td></li>    
    </tr>
{% empty %}
    <tr>Нет записей.</td>
{% endfor %}   
  </tbody>
</table>
{% endblock %}

awards/templates/awards/search.html
  
{% extends 'base_i.html' %}

{% load static %}

{% block header %}
 <header class="site-header">
        <div class="nav-bar">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                        <div class="site-branding d-flex align-items-center">
                           <a class="d-block" href="{% url 'index'%}" rel="home"><img class="d-block" src="{% static 'images/logo.png'%}" alt="logo"></a>
                        </div><!-- .site-branding -->

                        <nav class="site-navigation d-flex justify-content-end align-items-center">
                            <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-items-center">
                                <li class="current-menu-item"><a href="{% url 'index'%}">Главная</a></li>
                                <li><a href="{% url 'all_report' %}">Пример отчета</a></li>
                                <li><a href="{% url 'form_report' %}">Форма для отчета</a></li>
                                <li><a href="/admin/">База данных</a></li>

                                <li class="call-btn button gradient-bg mt-3 mt-md-0">
                                    <a class="d-flex justify-content-center align-items-center" href="#"><img src="{% static 'images/emergency-call.png'%}"> +7 987052863</a>
                                </li>
                            </ul>
                        </nav><!-- .site-navigation -->

                        <div class="hamburger-menu d-lg-none">
                            <span>Награды</span>
                            <span>Сотрудники</span>
                            <span></span>
                            <span></span>
                        </div><!-- .hamburger-menu -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .nav-bar -->

        <img class="header-img" src="{% static 'images/elements-bg.png'%}" alt="">
 </header><!-- .site-header -->
{% endblock %}

{% block content %}
    <div class="container">
<div class="row elements-wrap">
            <div class="col-12">
                <header class="entry-header elements-heading">
                    <h2 class="entry-title">Форма для отчета</h2>
                </header>

                <div class="entry-content elements-container">
                    <div class="row">
                          <div class="col-12 col-md-6">
                            <form method="POST">
                              {% csrf_token %} 
                              {{ form.as_p }}
                              <input type="submit" value="Поиск" class="button gradient-bg">
                            </form> 
                          </div>
                        <div class="col-12 col-md-6">
                           <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">Вх. №</th>
                                <th scope="col">Вх. дата</th>
                                <th scope="col">ФИО</th>
                              </tr>
                            </thead>
                            <tbody>
                          {% for doct in queryset %}
                              <tr>
                                <td>{{doct.incoming_num}}</td>   
                                <td>{{doct.incoming_date|date}}</td> 
                                <td>{{doct.doctor}}</td> 
                              </tr>
                          {% empty %}
                              <tr>Нет записей.</td>
                          {% endfor %}   
                            </tbody>
                          </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 </div>  

{% endblock %}

awards/templates/base.html
  
{% extends 'bootstrap4.html' %}

{% load bootstrap4 %}

{% block bootstrap4_content %}
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
<a class="navbar-brand" href="#">DoctorAwards</a>
 <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/">Список врачей</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/admin/">Панель управления</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'all_report' %}">Сводный отчет</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'form_report' %}">Форма для отчета</a>
    </li>
  </ul>
  </nav>
    <div class="container">
        <h1>{% block title %}{% endblock %}</h1>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% if request.user.is_authenticated %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% else %}
    GUEST
    {% endif %}   {% endblock %}
   
<script>
  $(function () {
    $("#id_date").datepicker({
      format:'dd/mm/yyyy',
    });
  });
</script>

awards/templates/base_i.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Page title -->
    <title>{% block title %}DoctorAward{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script src="{% static 'js/custom.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="{% static 'images/favicon.ico'%}" type="image/x-icon">
</head>
<body class="single-page elements-page">
    {% block header %} {% endblock %}
    {% block content %} {% endblock %}
    {% block footer %} {% endblock %}

    <script type='text/javascript' src="{% static 'js/jquery.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.collapsible.min.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/swiper.min.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.countdown.min.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/circle-progress.min.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.countTo.min.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.barfiller.js'%}"></script>
    <script type='text/javascript' src="{% static 'js/custom.js'%}"></script>
    {% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
    {{ form.media }}  

  </body>
</html>

awards/templates/bootstrap4.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Page title -->
    <title>{% block bootstrap4_title %}DoctorAward{% endblock %}</title>

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}

    <!-- Bootstrap JavaScript if it is in head -->
    {% if 'javascript_in_head'|bootstrap_setting %}
        {% bootstrap_javascript %}
    {% endif %}
    
    
    {% block bootstrap4_extra_head %}{% endblock %}


</head>

<body>
{% block bootstrap4_before_content %}{% endblock %}
{% block bootstrap4_content %} CONTENT {% endblock %}
{% block bootstrap4_after_content %}{% endblock %}

<!-- Bootstrap JavaScript if it is in body -->
{% if not 'javascript_in_head'|bootstrap_setting %}
    {% bootstrap_javascript %}
{% endif %}

{% block bootstrap4_extra_script %}{% endblock %}

{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}  
</body>

</html>

awards/templates/index.html
{% extends 'base_i.html' %}

{% load static %}
{% block header %}
 <header class="site-header">
        <div class="nav-bar">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                        <div class="site-branding d-flex align-items-center">
                           <a class="d-block" href="{% url 'index'%}" rel="home"><img class="d-block" src="{% static 'images/logo.png'%}" alt="logo"></a>
                        </div><!-- .site-branding -->

                        <nav class="site-navigation d-flex justify-content-end align-items-center">
                            <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-items-center">
                                <li class="current-menu-item"><a href="{% url 'index'%}">Главная</a></li>
                                <li><a href="{% url 'all_report' %}">Пример отчета</a></li>
                                <li><a href="{% url 'form_report' %}">Форма для отчета</a></li>
                                <li><a href="/admin/">База данных</a></li>

                                <li class="call-btn button gradient-bg mt-3 mt-md-0">
                                    <a class="d-flex justify-content-center align-items-center" href="#"><img src="{% static 'images/emergency-call.png'%}"> +7 987052863</a>
                                </li>
                            </ul>
                        </nav><!-- .site-navigation -->

                        <div class="hamburger-menu d-lg-none">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div><!-- .hamburger-menu -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .nav-bar -->

        <div class="swiper-container hero-slider">
            <div class="swiper-wrapper">
                <div class="swiper-slide hero-content-wrap" style="background-image: url('{% static 'images/hero.jpg'%}')">
                    <div class="hero-content-overlay position-absolute w-100 h-100">
                        <div class="container h-100">
                            <div class="row h-100">
                                <div class="col-12 col-lg-6 d-flex flex-column justify-content-center align-items-start">
                                    <header class="entry-header">
                                        <h2>Программа <br>учета медицинских наград</h2>
                                    </header><!-- .entry-header -->

                                    <div class="entry-content mt-4">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
                                    </div><!-- .entry-content -->

                                    <footer class="entry-footer d-flex flex-wrap align-items-center mt-4">
                                        <a href="/admin/" class="button gradient-bg">Войти</a>
                                    </footer><!-- .entry-footer -->
                                </div><!-- .col -->
                            </div><!-- .row -->
                        </div><!-- .container -->
                    </div><!-- .hero-content-overlay -->
                </div><!-- .hero-content-wrap -->

            <div class="pagination-wrap position-absolute w-100">
                <div class="swiper-pagination d-flex flex-row flex-md-column"></div>
            </div><!-- .pagination-wrap -->
        </div><!-- .hero-slider -->

 </header><!-- .site-header -->
{% endblock %}


{% block content %}
<div class="homepage-boxes">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="opening-hours">
                        <h2 class="d-flex align-items-center">Количество наград</h2>

                        <ul class="p-0 m-0">
                            <li>Всего: <span>100</span></li>
                            <li>Утверждено <span>50</span></li>
                            <li>На расмотрении <span>25</span></li>
                            <li>Отклонено <span>25</span></li>
                        </ul>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                    <div class="emergency-box">
                        <h2 class="d-flex align-items-center">Справка</h2>

                        <div class="call-btn button gradient-bg">
                            <a class="d-flex justify-content-center align-items-center" href="#"><img src="{% static 'images/emergency-call.png'%}"> +34 586 778 8892</a>
                        </div>

                        <p>Lorem ipsum dolor sit amet, cons ectetur adipiscing elit. Donec males uada lorem maximus mauris sceler isque, at rutrum nulla.</p>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-5 mt-5 mt-lg-0">
                    <div class="appointment-box">
                        <h2 class="d-flex align-items-center">Поиск награды</h2>

                        <form class="d-flex flex-wrap justify-content-between">
                            <select class="select-department">
                                <option value="value1">Select Department</option>
                                <option value="value2">Select Department 1</option>
                                <option value="value3">Select Department 2</option>
                            </select>

                            <select class="select-doctor">
                                <option>Select Doctor</option>
                                <option>Select Doctor 1</option>
                                <option>Select Doctor 2</option>
                            </select>

                            <input type="text" placeholder="Name">

                            <input type="number" placeholder="Phone No">

                            <input class="button gradient-bg" type="submit" value="Найти">
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block footer%}
      <footer class="site-footer" style="background-image: url('{% static 'images/footer-bg.png'%}') no-repeat center #fff">
        <div class="footer-widgets">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="foot-about">
                            <h2><a href="{% static 'index'%}"><img src="{%static 'images/logo.png'%}" alt=""></a></h2>

                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien.</p>

                            
                        </div><!-- .foot-about -->p clas
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-4 mt-5 mt-md-0">
                        <div class="foot-contact">
                            <h2>Contact</h2>

                            <ul class="p-0 m-0">
                                <li><span>Addtress:</span>Mitlton Str. 26-27 London UK</li>
                                <li><span>Phone:</span>+53 345 7953 32453</li>
                                <li><span>Email:</span>yourmail@gmail.com</li>
                            </ul>
                        </div>
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-4 mt-5 mt-md-0">
                        <div class="foot-links">
                            <h2>Usefull Links</h2>

                            <ul class="p-0 m-0">
                                <li><a href="{% static 'index'%}">Home</a></li>
                                <li><a href="about.html">About us</a></li>
                                <li><a href="#">Departments</a></li>
                                <li><a href="contact.html">Contact</a></li>
                                <li><a href="news.html">FAQ</a></li>
                                <li><a href="services.html">Testimonials</a></li>
                            </ul>
                        </div><!-- .foot-links -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .footer-widgets -->
    </footer><!-- .site-footer -->
    {% endblock%}